version: "3"

services:
  dev_db:
    image: postgres:9.5
    volumes:
      - /tmp/dev_db:/var/lib/psql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=service_portal_development
    ports:
      - 5435:5432
  test_db:
    image: postgres:9.5
    volumes:
      - /tmp/test_db:/var/lib/psql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=service_portal_test
    ports:
      - 5436:5432
